### ISSUE TITLE
Title not populating in alerts

### ISSUE THREAD

**Issue by adamstauffer** [dunbarcyber/cyphon#152]
Context: I'm trying to ingest results from Nessus via [nessusbeat](https://github.com/darvid/nessusbeat). I have alerts populating in the database and frontend, however the alert's title doesn't show properly via the taste (shows "No title available").

Here's my configuration:

- Nessus data goes to both Elasticsearch and RabbitMQ. Looks like the following in Elasticsearch:

```
{
  @timestamp: "",
  @uuid: "",
  @version: "",
  _id: "",
  _index: "",
  _score: "",
  _type: "",
  beat {
    hostname: "",
    name: "",
    version: ""
  }
  collection: "",
  cve: "",
  cvss: "",
  description: "",
  host: "",
  name: "",
  plugin_id: "",
  plugin_output: "",
  port: "",
  protocol: "",
  risk: "",
  see_also: "",
  solution: "",
  synopsis: "",
  tags: "",
  type: ""
}
```
I'm trying to get the "name" field above to show as the title in the alert.

- I have a container named "nessus" that looks like

```
{
    "created_date": "DateTimeField (DateTime)",
    "cve": "CharField",
    "cvss": "FloatField",
    "description": "TextField (Keyword)",
    "host_ip": "GenericIPAddressField (IPAddress)",
    "plugin_id": "CharField",
    "plugin_name": "CharField (Keyword)",
    "plugin_output": "TextField (Keyword)",
    "port": "CharField",
    "protocol": "CharField (Keyword)",
    "risk": "CharField",
    "see_also": "CharField (Keyword)",
    "solution": "TextField (Keyword)",
    "synopsis": "CharField (Keyword)"
}
```

Had to create a BottleField called "plugin_name" because "name" already exists (and used for Twitter). But should be able to use a condenser/data parser to copy the field right?

- I'm using a condenser w/ data parsers to copy each field (not sure if this is necessary) as such:

```
ˣ cve (CharField) > cve__COPY
ˣ cvss (FloatField) > cvss__COPY
ˣ description (TextField) > description__COPY
ˣ host_ip (GenericIPAddressField) > host__COPY
ˣ plugin_id (CharField) > plugin_id__COPY
ˣ plugin_name (CharField) > name__COPY
ˣ plugin_output (TextField) > plugin_output__COPY
ˣ port (CharField) > port__COPY
ˣ protocol (CharField) > protocol__COPY
ˣ risk (CharField) > risk__COPY
ˣ see_also (CharField) > see_also__COPY
ˣ solution (TextField) > solution__COPY
ˣ synopsis (CharField) > synopsis__COPY
ˣ created_date (DateTimeField) > timestamp__copy
```
The name__COPY data parser looks like:

```
Name > name__COPY
Source field(s) > name
Method > Copy
Regex > (empty)
Formatter > (empty)
```

- Finally, the Taste on my Container looks like:

```
Author > host_ip
Title	> plugin_name
Content > description
Datetime	> created_date
```

I tried switching the taste to use "synopsis" and that worked/rendered the title. The only difference I notice is that the BottleField's name matched the field in the raw data, whereas that isn't the case now (plugin_name vs. name)

**Comment by lhadjchikh** [comment]
The condenser is only used when parsing and saving the data with a munger ("schema on write"). Unfortunately, using a condenser to do "schema on read" on previously saved data won't work (although I'd like to implement that in the future). Consequently, the fields of the container will have to match the fields in Elasticsearch for Cyphon to retrieve those fields.

However, you should be able to reuse the "name" BottleField that already exists. BottleFields can be used in multiple containers, as long as the field_type makes sense (Elasticsearch doesn't permit fields with the same name to have multiple data types). Alternatively, you could change the field name in nessusbeat to "plugin_name".

**Comment by adamstauffer** [comment]
ok figured it was something like this. because the field_type was different (account vs. keyword) i couldnt re-use the bottlefield. I'll go the second route, maybe using logstash to mutate the field name. feel free to close

**Comment by lhadjchikh** [comment]
You could also just set the target_type to null. That field is only in place for a future feature, so it won't break anything if you change it.
