### ISSUE TITLE
muzzled alerts (incidents) should re-open original alerts

### ISSUE THREAD

**Issue by adamstauffer** [dunbarcyber/cyphon#164]
When I'm ingesting Nessus results, I can get alerts successfully. If I close one of the alerts as "completed" then re-run my scans (without changing anything), the alerts incidents get incremented correctly. However, the alert's status doesn't change. IMO, the alert should get its status reset to "new" (or maybe a new status/outcome like "regression"). I'm not sure if this should happen for all outcomes (maybe it shouldn't do this for "False Positive?"), so maybe this should be something you can configure which cases you want alerts to be re-opened as a part of the muzzle.

**Comment by lhadjchikh** [comment]
Good point, thanks!

**Comment by censey** [comment]
Could you provide a little bit of clarification... How frequently are you going to be running these scans in succession?  hourly, daily, weekly?  If that is the case, you could just configure the existing muzzles shorter than your scan interval.  Wouldn't this produce the desired result?

**Comment by adamstauffer** [comment]
We do have scans running on regular intervals... daily, weekly, etc. However, we also run scans on-demand as well. I'm sure we could play with the muzzle intervals more. In the event that the interval was shorter than the scan interval, then we would still get duplicate alerts even if the original alert wasn't closed. This is assuming we don't get all alerts investigated by the time the next scan runs. This could compound and lead to the alert bloat which we are trying to use muzzles to get around

**Comment by adamstauffer** [comment]
another case for consideration - lets say I have alerts coming from failed login attempts for a particular user. if i investigate with the user and determine the login attempts were legitimate, i close the alert. if 5 minutes later (or any time within my muzzle interval) a legitimate brute force attack occurs on this user account, im blind to it because ive already closed my original alert and am unaware that more incidents are being generated.

the counter-argument to the above case is "well you probably shouldnt be using muzzles on this dataset then" or "shorten your muzzle interval to the lowest valuable you are comfortable with". however, there are other cases in this dataset where muzzles with longer intervals are serving their desired purpose

my question is - would it be too simple to just create a new alert during incident creation if status != Done? or are there plans to support generic workflows/user defined states for alerts where hardcoding this would be bad? i could probably submit a PR for exactly this but if it needs to get fancy (like having a completely new module for transitioning alerts or a new status for "regressions") then i wanted to check first

**Comment by fatalglitch** [comment]
The watchdog should trigger the new brute force alerts with a different src_ip, which would then be identified as a seperate event by the muzzle. I think what @censey recommended is best, to establish the proper muzzle configuration and timing to properly suppress.

If you are seeing more alerts than you expect, and they are providing limited value, you can also modify the data rules/sieve for the watchdog to not include alerting when the src_ip is from your known scanner IP

**Comment by adamstauffer** [comment]
i think i am going to play with the muzzles a bit more. I think i also need to have different watchdogs for the large and variable amount of data coming from this data source. this will allow me to configure different muzzles depending on the fields that are present within the data. thanks
