### ISSUE TITLE
Unsupported Hardware Family

### ISSUE THREAD

**Issue by DigiAngel** [dunbarcyber/cyphon#176]
Hey all!

So in trying to import the ova we are getting:

Unsupported hardware family 'virtualbox-2.2'.

Any way to fix this?  Thank you.

**Comment by lhadjchikh** [comment]
We updated the OVA, so you might be trying to use an old version. Try [this](https://s3.amazonaws.com/cyphon-public/vms/Cyphon-20170725.ova).

**Comment by DigiAngel** [comment]
Ah thank you I'll give that a go.

**Comment by DigiAngel** [comment]
Worked like a champ thank you!
