### ISSUE TITLE
Mass delete of alerts causing 400

### ISSUE THREAD

**Issue by robinlennox** [dunbarcyber/cyphon#232]
When I try and delete a large number of alarms... in this case over 2000 I get a 400 error.

![screenshot from 2017-09-21 09-45-24](https://user-images.githubusercontent.com/5493700/30669293-e7f4bcb4-9eb1-11e7-864c-3c5f5b67973f.png)
![screenshot from 2017-09-21 09-45-37](https://user-images.githubusercontent.com/5493700/30669297-ea2b9430-9eb1-11e7-820e-a71a8ade40e1.png)

**Comment by lhadjchikh** [comment]
Try adding the ``DATA_UPLOAD_MAX_NUMBER_FIELDS`` setting to your ``cyphon/settings/base.py`` file, and set it to either ``None`` or some number exceeding the maximum number of alerts you think you'll want to delete. (You can read more about this setting [here](https://docs.djangoproject.com/en/1.11/ref/settings/#data-upload-max-number-fields).) Then restart your cyphon service: ``sudo docker-compose restart cyphon``. Hopefully that will fix it...

**Comment by robinlennox** [comment]
That worked when setting DATA_UPLOAD_MAX_NUMBER_FIELDS = None.  I think there should be an option in conf.py to allow this value to be tweaked in Cyphon.

**Comment by lhadjchikh** [comment]
Thanks for the suggestion!  I could add this and the ``DATA_UPLOAD_MAX_MEMORY_SIZE`` setting to the ``base.py`` settings file, which contains the settings for Django and other third-party packages used by Cyphon. For maintainability reasons, I try to reserve the ``conf.py`` file primarily for settings used by the Cyphon codebase itself, so I don't get confused about which settings are used by Cyphon and which are used by required packages.

Django has tons of optional settings (listed [here](https://docs.djangoproject.com/en/1.11/ref/settings/)), so any of the more commonly used settings could be added to ``base.py`` if it makes life easier for people.

**Comment by lhadjchikh** [comment]
Added data upload settings in https://github.com/dunbarcyber/cyphon/pull/233.
