### ISSUE TITLE
Elasticsearch issue with docker

### ISSUE THREAD

**Issue by suomikaveri** [dunbarcyber/cyphon#303]
Posted this in cyphondock as well:

Hello.
I installed Cyphon on 2 separate machines via Cyphondock. However, the elasticsearch is not working on neither one of them.
I get HTTP 500-error when I try to add a collection.
Here's the main elasticsearch error: [36melasticsearch_1 |�[0m Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes

Here's the nginx main error:
[22/Nov/2017:04:59:03 +0000] "POST /admin/warehouses/collection/add/?_to_field=id&_popup=1 HTTP/1.1" 500 27 "http://localhost/admin/warehouses/collection/add/?_to_field=id&_popup=1" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"

Is docker trying to work outside of it's container, or what is causing the issue?
I didn't have that folder mentioned. I created it, applied chmod but it still doesn't work. Nothing is being created under that folder. I'm running default settings
Java docs: "Checked exception thrown **when a file system operation is denied**, typically due to a file permission or other access check. "

**Comment by lhadjchikh** [comment]
Handling this in https://github.com/dunbarcyber/cyphondock/issues/54.
