### ISSUE TITLE
No module named autocomplete_light

### ISSUE THREAD

**Issue by suomikaveri** [dunbarcyber/cyphon#305]
Hey. I'm trying to do a manual installation of Cyphon. I don't have much experience with Python, so noob advice is welcome.
Here's the error that I get:

File "/home/petu/.local/lib/python2.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
**ImportError: No module named autocomplete_light**

I tried "pip install django-autocomplete-light" and also installing it from github version, but I still get that same error when running "python manage.py migrate". I also tried python3 versions, didn't work either.
What should I do?

**Comment by lhadjchikh** [comment]
If you're doing a manual install,  I'd recommend installing all the required packages within a Python 3 virtual environment. See Python's docs on [virtual environments](https://docs.python.org/3/tutorial/venv.html) for instructions.

Once you've activated your virtual environment, install all the packages from Cyphon's `requirements.txt` file:
```
$ pip install -r /path-to-cyphon-directory/cyphon/requirements.txt
```
Then try to run migrations again.

**Comment by lhadjchikh** [comment]
Closing this out. Feel free to reopen if it's still an issue.
