### ISSUE TITLE
Alert from email. attachment doesn't work.

### ISSUE THREAD

**Issue by trenerok** [dunbarcyber/cyphon#403]
Hello. I have a problem with attachments when i generated alerts from email. 

I acted strictly according to the instructions but I receive an alert only when there is no attachment in the email message. All fields are created in accordance with the instruction. If I make a test and copy the body of the message to the mail condenser (test), I see the converted fields and the attachment field with a link to my attachment. However, when I send a message with an attachment, it does not work ..

Maybe you have any ideas for resolve my problem?

i use latest version CYphon. I installed it from cyphondock (docker)

**Comment by lhadjchikh** [comment]
Hi @trenerok, can you confirm that the type of attachment is allowed in the [`MAILSIFTER` settings](https://github.com/dunbarcyber/cyphon/blob/master/cyphon/cyphon/settings/conf.example.py#L197-L198)?:
```
MAILSIFTER = {
    ...
    'ALLOWED_EMAIL_ATTACHMENTS': ('text/plain', 'application/pdf', 'image/jpeg', 'image/png'),
    'ALLOWED_FILE_EXTENSIONS': ('.txt', '.pdf', '.jpeg', '.jpg', '.png'),
    ...
}
```

**Comment by trenerok** [comment]
@lhadjchikh. Thank you very much for your tips. I use `docker logs -f cyphondock_celeryworker_1` to watching errors. 
The error was in the rights to the folder usr/src/app/media in cyphondock_cyphon_1 container.

**Comment by lhadjchikh** [comment]
Great, thanks for letting us know! I'll add a note about that in the documentation.
