### ISSUE TITLE
Can I create a new dashboard?

### ISSUE THREAD

**Issue by santi10** [dunbarcyber/cyphon#466]
Hi,

Can I create a new dashboards????

Thx

**Comment by chasepbrewer** [comment]
No, but that is something we can add to the backlog of features if it's requested enough.

Since the data would be stored in elasticsearch, you can use other open source tools like Kibana or Grafana to display dashboards from your data.

**Comment by santi10** [comment]
ok, Thank you very much

**Comment by santi10** [comment]
fix
