### ISSUE TITLE
Compare two/n different emails( content or subject )

### ISSUE THREAD

**Issue by sajeeshgit** [dunbarcyber/cyphon#484]
Hi team,

A quick question, can we compare two/n emails coming in a different time stamp and generate alert. Need to compare few strings in the content of the emails and if it matches the logic, then generate an alert. Please let me know.

Thanks.

**Comment by sajeeshgit** [comment]
It can hold the alert when the state of the content in the mail is warning and generate alert only when the state of the content in the mail changes to Critical.

**Comment by chasepbrewer** [comment]
That functionality isn't possible at this time. Documents are ingested, parsed, and alerted on their way to long form persistent storage in either elasticsearch or mongo without any intermediary storage. The only things that are stored from Cyphon are the alerts in a postgresql database, which allow for things like alert incident counts and comparisons between data that triggered alerts.

**Comment by chasepbrewer** [comment]
Closing issue. I've put this functionality into our current feature backlog. Feel free to reopen if you have any follow up questions.
