### ISSUE TITLE
Configure logstash.conf file for JSON input from Filebeat

### ISSUE THREAD

**Issue by p3nreel** [dunbarcyber/cyphon#547]
Hello, would someone be able to assist with writing/configuring the logstash.conf file to ingest ONLY the text/strings highligted in the image? Filebeat will be forwarding JSON logs to a separate server that has  Cyphon Docker installed. After performing many Google searches, I am not able to find a good example. Currently the below is all that I have so far. Thank you!

input {
    beats { port => 5044 }
}        

type => json
    }
}

filter {
   grok {

{

    source 
	

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
	user =>
	password => ""
  }
  
  stdout {
    codec =>
	}
}

  source

![capture](https://user-images.githubusercontent.com/19589960/40497917-78080aa4-5f4b-11e8-8414-ebef7bcbb19f.JPG)

**Comment by fatalglitch** [comment]
I recommend you post this to the elastic discuss forums: https://discuss.elastic.co/c/logstash

**Comment by p3nreel** [comment]
Thanks will do.
